#
# Copyright (C) 2008-2016 The fjqingyou <fjqingyou@gmail.com>
#
# This is free software, licensed under the MIT License.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Whistle
LUCI_PKGARCH:=all

PKG_LICENSE:=MIT

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
